[theme]
# Primary accent color for interactive elements.
primaryColor = "#FDBFD5"

# Background color for the main content area.
backgroundColor = "#1D1D1D"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#fff"